GROQ_API_KEY = "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"
TAVILY_API_KEY = "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"
GEMINI_API_KEY = "AIzaSyCST5jj1xiE79fEDyrsbhV4xmqBik089KM"
AUTH_MAX_DURATION_SECONDS = 300
AUTH_TMP_DIR= "/tmp"
AUTH_LOG_LEVEL = "INFO"