version: "3.8"
services:
  app:
    build: .
    # make sure your app listens on 0.0.0.0:5001 inside the container
    environment:
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    volumes:
      - ./:/app
    restart: unless-stopped

  caddy:
    image: caddy:2.7.4
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      ACME_AGREE: "true"
    env_file:
      - .env
    restart: unless-stopped

  cloudflared_ephemeral:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --url http://caddy:8080

volumes:
  caddy_data:
  caddy_config:
