version: "3.8"
services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./:/app
    restart: unless-stopped


