services:
  app:
    build: .
    environment:
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    volumes:
      - ./:/app
    restart: unless-stopped

  cloudflared_ephemeral:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --url http://app:5001

volumes: {}
